// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package gendb

import (
	"context"

	"github.com/TulgaCG/add-drop-classes-api/pkg/types"
)

type Querier interface {
	CreateRole(ctx context.Context, role string) (Role, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteRole(ctx context.Context, role string) (int64, error)
	GetUser(ctx context.Context, id types.UserID) (GetUserRow, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	GetUserCredentialsWithUsername(ctx context.Context, username string) (User, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	UpdateToken(ctx context.Context, arg UpdateTokenParams) (UpdateTokenRow, error)
	UpdateTokenExpirationDate(ctx context.Context, arg UpdateTokenExpirationDateParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
}

var _ Querier = (*Queries)(nil)
