// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: role_queries.sql

package gendb

import (
	"context"

	"github.com/TulgaCG/add-drop-classes-api/pkg/types"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (role) VALUES ($1)
RETURNING id, role
`

func (q *Queries) CreateRole(ctx context.Context, role types.Role) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, role)
	var i Role
	err := row.Scan(&i.ID, &i.Role)
	return i, err
}

const deleteRole = `-- name: DeleteRole :execrows
DELETE FROM roles WHERE role = $1
`

func (q *Queries) DeleteRole(ctx context.Context, role types.Role) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRole, role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, role FROM roles WHERE role = $1
`

func (q *Queries) GetRoleByName(ctx context.Context, role types.Role) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, role)
	var i Role
	err := row.Scan(&i.ID, &i.Role)
	return i, err
}
