// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: user_queries.sql

package gendb

import (
	"context"
	"database/sql"

	"github.com/TulgaCG/add-drop-classes-api/pkg/types"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, password
) VALUES (
    ?, ?
)
RETURNING id, username
`

type CreateUserParams struct {
	Username string `db:"username" json:"username"`
	Password string `db:"password" json:"password"`
}

type CreateUserRow struct {
	ID       types.UserID `db:"id" json:"id"`
	Username string       `db:"username" json:"username"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Password)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Username)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username FROM users
WHERE id = ? LIMIT 1
`

type GetUserRow struct {
	ID       types.UserID `db:"id" json:"id"`
	Username string       `db:"username" json:"username"`
}

func (q *Queries) GetUser(ctx context.Context, id types.UserID) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(&i.ID, &i.Username)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username FROM users
WHERE username = ? LIMIT 1
`

type GetUserByUsernameRow struct {
	ID       types.UserID `db:"id" json:"id"`
	Username string       `db:"username" json:"username"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(&i.ID, &i.Username)
	return i, err
}

const getUserCredentialsWithUsername = `-- name: GetUserCredentialsWithUsername :one
SELECT id, username, password, token, token_expire_at FROM users
WHERE username = ? LIMIT 1
`

func (q *Queries) GetUserCredentialsWithUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserCredentialsWithUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Token,
		&i.TokenExpireAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username FROM users
ORDER BY username
`

type ListUsersRow struct {
	ID       types.UserID `db:"id" json:"id"`
	Username string       `db:"username" json:"username"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateToken = `-- name: UpdateToken :one
UPDATE users
set token = ?,
    token_expire_at = ?
WHERE id = ?
RETURNING username, token
`

type UpdateTokenParams struct {
	Token         sql.NullString `db:"token" json:"token"`
	TokenExpireAt sql.NullTime   `db:"token_expire_at" json:"tokenExpireAt"`
	ID            types.UserID   `db:"id" json:"id"`
}

type UpdateTokenRow struct {
	Username string         `db:"username" json:"username"`
	Token    sql.NullString `db:"token" json:"token"`
}

func (q *Queries) UpdateToken(ctx context.Context, arg UpdateTokenParams) (UpdateTokenRow, error) {
	row := q.db.QueryRowContext(ctx, updateToken, arg.Token, arg.TokenExpireAt, arg.ID)
	var i UpdateTokenRow
	err := row.Scan(&i.Username, &i.Token)
	return i, err
}

const updateTokenExpirationDate = `-- name: UpdateTokenExpirationDate :exec
UPDATE users
set token_expire_at = ?
WHERE id = ?
`

type UpdateTokenExpirationDateParams struct {
	TokenExpireAt sql.NullTime `db:"token_expire_at" json:"tokenExpireAt"`
	ID            types.UserID `db:"id" json:"id"`
}

func (q *Queries) UpdateTokenExpirationDate(ctx context.Context, arg UpdateTokenExpirationDateParams) error {
	_, err := q.db.ExecContext(ctx, updateTokenExpirationDate, arg.TokenExpireAt, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
set username = ?,
password = ?
WHERE id = ?
RETURNING id, username
`

type UpdateUserParams struct {
	Username string       `db:"username" json:"username"`
	Password string       `db:"password" json:"password"`
	ID       types.UserID `db:"id" json:"id"`
}

type UpdateUserRow struct {
	ID       types.UserID `db:"id" json:"id"`
	Username string       `db:"username" json:"username"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.Username, arg.Password, arg.ID)
	var i UpdateUserRow
	err := row.Scan(&i.ID, &i.Username)
	return i, err
}
