CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    token VARCHAR(64),
    token_expire_at DATETIME
);

CREATE TABLE IF NOT EXISTS user_roles(
    id INTEGER PRIMARY KEY,
    user_id INTEGER NOT NULL,
    role_id VARCHAR(255) NOT NULL,
    UNIQUE(user_id,role_id),
    FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (role_id) REFERENCES roles(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS roles(
    id INTEGER PRIMARY KEY,
    role VARCHAR(255) NOT NULL UNIQUE
);